export var INIT = 'INIT';

export var PAVILION_ADD = 'PAVILION_ADD';
export var PAVILION_DELETE = 'PAVILION_DELETE';
export var PAVILION_DELETED = 'PAVILION_DELETED';
export var PAVILION_ADDED = 'PAVILION_ADDED';
export var PAVILION_SELECT = 'PAVILION_SELECT';
export var PAVILIONS_LOADED = 'PAVILIONS_LOADED';


export var BASE_LAYER_SET = 'BASE_LAYER_SET';
export var BASE_LAYER_SAVE = 'BASE_LAYER_SAVE';
export var BASE_LAYER_SAVED = 'BASE_LAYER_SAVED';
export var BASE_DISTANCE_SET = 'BASE_DISTANCE_SET'
export var BASE_DISTANCE_LENGTH_SET = 'BASE_DISTANCE_LENGTH_SET'


export var DRAWING_MODE_SET = 'DRAWING_MODE_SET'



export var ERROR_SET = 'ERROR_SET';

