export var INIT = 'INIT';

export var UNSELECT_ALL = 'UNSELECT_ALL';

export var PAVILION_ADD = 'PAVILION_ADD';
export var PAVILION_DELETE = 'PAVILION_DELETE';
export var PAVILION_DELETED = 'PAVILION_DELETED';
export var PAVILION_ADDED = 'PAVILION_ADDED';
export var PAVILION_SELECT = 'PAVILION_SELECT';
export var PAVILIONS_LOADED = 'PAVILIONS_LOADED';


export var BASE_LAYER_SET = 'BASE_LAYER_SET';
export var BASE_LAYER_SAVE = 'BASE_LAYER_SAVE';
export var BASE_LAYER_SAVED = 'BASE_LAYER_SAVED';
export var BASES_LOADED = 'BASES_LOADED';
export var BASE_DISTANCE_SET = 'BASE_DISTANCE_SET'
export var BASE_DISTANCE_LENGTH_SET = 'BASE_DISTANCE_LENGTH_SET'
export var BASE_GRID_GEOMETRY = 'BASE_GRID_GEOMETRY';


export var DRAWING_MODE_SET = 'DRAWING_MODE_SET'

export var OVERLAY_FEAT_ADD = 'OVERLAY_FEAT_ADD'
export var OVERLAYS_LOADED = 'OVERLAYS_LOADED'
export var OVERLAY_FEAT_UPDATE = 'OVERLAY_FEAT_UPDATE'
export var OVERLAY_FEAT_DELETE = 'OVERLAY_FEAT_DELETE'
export var OVERLAY_FEAT_ROTATE = 'OVERLAY_FEAT_ROTATE'
export var OVERLAY_FEAT_TEXT = 'OVERLAY_FEAT_TEXT'
export var OVERLAY_ROLLBACK = 'OVERLAY_ROLLBACK'
export var OVERLAY_SAVE = 'OVERLAY_SAVE'
export var OVERLAY_SAVED = 'OVERLAY_SAVED'
export var OVERLAY_FEAT_SELECT = 'OVERLAY_FEAT_SELECT'
export var OVERLAY_EDIT = 'OVERLAY_EDIT'
export var OVERLAY_TYPE_SELECT = 'OVERLAY_TYPE_SELECT'

export var STANDS_LOADED = 'STANDS_LOADED'
export var STAND_ADD = 'STAND_ADD'
export var STAND_ADDED = 'STAND_ADDED'
export var STAND_UPDATE = 'STAND_UPDATE'
export var STAND_UPDATED = 'STAND_UPDATED'
export var STAND_DELETE = 'STAND_DELETE'
export var STAND_DELETED = 'STAND_DELETED'
export var STAND_SELECT = 'STAND_SELECT'
export var STAND_EDIT = 'STAND_EDIT'
export var STAND_TYPE_UPDATE = 'STAND_TYPE_UPDATE'
export var STAND_POINTS_UPDATE = 'STAND_POINTS_UPDATE'


export var ERROR_SET = 'ERROR_SET';

